{{ if .is.personal -}}
workspaces:
  all:
    root: dev/ws
  share:
    root: .local/share
    repos:
      - name: pirpedro/dotfiles
        path: chezmoi
        streamdeck: true
  personal:
    root: dev/ws/my
    provider: git@github.com
    repos:
      - name: pirpedro/dev-gadgets
        streamdeck: 
          title: gadgets
      - name: pirpedro/features
        streamdeck: true
      - name: pirpedro/homelab
        streamdeck: 
          title: homelab
      - name: pirpedro/devcontainers
      - name: pirpedro/dotfiles
      - name: pirpedro/pirpedro.github.io
        path: blog/personal
      - name: psrandom/psrandom.github.io.git
        path: blog/psrandom
      - name: pirpedro/CEMEAI-USP
        path: MBA-CEMEAI/Disciplinas
      - name: pirpedro/CEMEAI_TCC
        path: MBA-CEMEAI/TCC
  archived:
    root: dev/ws/archived
    provider: git@github.com
    repos:
      - name: pirpedro/docker
      - name: pirpedro/bootstrapping
        path: rule-them-all
      - name: pirpedro/Inquirer.sh
      - name: pirpedro/bash-common
      - name: pirpedro/my-config
  fullcycle:
    root: dev/ws/fullcycle
    provider: git@github.com
    repos:
      - name: pirpedro/flix-catalog
        path: catalog
      - name: pirpedro/flix-encoder
        path: encoder
      - name: pirpedro/flix-auth
        path: micro-auth
      - name: pirpedro/flix-micro-catalog
        path: micro-catalog
      - name: pirpedro/flix-message-broker
        path: rabbitmq
  MDS:
    root: dev/ws/MDS
    provider: git@git.mds.gov.br
    repos:
      - name: uff/sisct-cadastro-nacional-web-src
        path: sisct-web
        streamdeck: 
          title: sisct web
      - name: uff/sisct-cadastro-nacional-api-src
        path: sisct-api
        streamdeck: 
          title: sisct api
  UFF:
    root: dev/ws/UFF
    provider: git@github.com
    repos:
      - name: pirpedro/pgfa
      - name: nees-uff/pef
      - name: b2in-tech/prepaf
      - name: nees-uff/prepaf
        path: polar-scout
      - name: b2in-tech/fund-of-funds
{{ end -}}
