[".local/share/zprezto"]
  type= "git-repo"
  url = "https://github.com/sorin-ionescu/prezto.git"
  refreshPeriod = "168h"
  [".local/share/zprezto".clone]
    args = ["--recursive"]
  [".local/share/zprezto".update]
    args = ["--recurse-submodules"]

[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".local/share/nvim/site/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".vim/bundle/Vundle.vim"]
  type = "git-repo"
  url = "https://github.com/VundleVim/Vundle.vim.git"
[".config/nano"]
  type = "archive"
  url = "https://github.com/scopatz/nanorc/archive/master.tar.gz"
  stripComponents=1
  include=["*.nanorc"]
{{- if and (eq .chezmoi.os "linux") .is.personal (not .is.ephemeral) }}
{{- $ageVersion := "1.0.0" }}
[".local/bin/age"]
  type = "file"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable = true
  [".local/bin/age".filter]
      command = "tar"
      args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age"]
[".local/bin/age-keygen"]
  type = "file"
  url = "https://github.com/FiloSottile/age/releases/download/v{{ $ageVersion }}/age-v{{ $ageVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
  executable = true
  [".local/bin/age-keygen".filter]
      command = "tar"
      args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "age/age-keygen"]
[".config/ulauncher/user-themes/ReMatch-Dark-Blue-Ulauncher"]
  type = "git-repo"
  url = "git@github.com:S-ci/ReMatch-Dark-Blue-Ulauncher.git"
{{- end }}
{{- template "custom/themes" . }}
{{- template "custom/gitprojects" . }}