version = 3

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
template = ' '
background = 'transparent'

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = ' '

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
leading_diamond = '╭─'
template = ' {{ .Name }} '
foreground = '#ffffff'
background = '#0077c2'
type = 'shell'
style = 'diamond'

[[blocks.segments]]
template = '<parentBackground></>  '
foreground = '#FFFB38'
background = '#ef5350'
type = 'root'
style = 'diamond'

[[blocks.segments]]
template = '  {{ path .Path .Location }} '
foreground = '#e4e4e4'
powerline_symbol = ''
background = '#3465a4'
type = 'path'
style = 'powerline'

[blocks.segments.properties]
folder_icon = '  '
home_icon = ''
style = 'letter'

[[blocks.segments]]
template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#ef5350>  {{ .Staging.String }}</>{{ end }} '
foreground = '#000000'
powerline_symbol = ''
background = '#4e9a06'
type = 'git'
style = 'powerline'
background_templates = [
  '{{ if or (.Working.Changed) (.Staging.Changed) }}#c4a000{{ end }}',
  '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}',
  '{{ if gt .Ahead 0 }}#89d1dc{{ end }}',
  '{{ if gt .Behind 0 }}#4e9a06{{ end }}',
]

[blocks.segments.properties]
branch_icon = ''
fetch_status = true
fetch_upstream_icon = true

[[blocks.segments]]
trailing_diamond = ''
template = '  {{ .FormattedMs }}⠀'
foreground = '#ffffff'
background = '#83769c'
type = 'executiontime'
style = 'diamond'

[blocks.segments.properties]
style = 'roundrock'
threshold = 0.0

[[blocks]]
type = 'prompt'
alignment = 'right'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ .Full }}'
foreground = '#3C873A'
background = '#303030'
type = 'node'
style = 'diamond'

[blocks.segments.properties]
fetch_package_manager = true
npm_icon = ' <#cc3a3a></> '
yarn_icon = ' <#348cba></>'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
foreground = '#FFE873'
background = '#306998'
type = 'python'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#ffffff'
background = '#0e8ac8'
type = 'java'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#0d6da8'
background = '#0e0e0e'
type = 'dotnet'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#06aad5'
background = '#ffffff'
type = 'go'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#925837'
background = '#f3f0ec'
type = 'rust'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#055b9c'
background = '#e1e8e9'
type = 'dart'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ' '
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#ce092f'
background = '#ffffff'
type = 'angular'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ' '
trailing_diamond = ' '
template = 'α {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#de1f84'
background = '#ffffff'
type = 'aurelia'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ' '
trailing_diamond = ' '
template = '{{ if .Error }}{{ .Error }}{{ else }}Nx {{ .Full }}{{ end }}'
foreground = '#ffffff'
background = '#1e293b'
type = 'nx'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ' '
trailing_diamond = ' '
template = '<#ca3c34></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#359a25'
background = '#945bb3'
type = 'julia'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#9c1006'
background = '#ffffff'
type = 'ruby'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = '<#f5bf45></> {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}'
foreground = '#5398c2'
background = '#ffffff'
type = 'azfunc'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ' '
template = ' {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'
foreground = '#faa029'
background = '#565656'
type = 'aws'
style = 'diamond'

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = ' {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}'
foreground = '#ffffff'
background = '#316ce4'
type = 'kubectl'
style = 'diamond'

# [[blocks.segments]]
# leading_diamond = ''
# trailing_diamond = '<transparent,background></>'
# template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '
# foreground = '#222222'
# background = '#b2bec3'
# type = 'os'
# style = 'diamond'

# [blocks.segments.properties]
# linux = ''
# macos = ''
# windows = ''

[[blocks.segments]]
leading_diamond = '<transparent,background></>'
trailing_diamond = '<transparent,background></>'
template = '{{ .FormattedMs }}⠀'
foreground = 'yellow'
background = 'transparent'
type = 'executiontime'
style = 'diamond'

[blocks.segments.properties]
style = 'austin'
threshold = 1000

[[blocks.segments]]
template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }} '
foreground = '#262626'
powerline_symbol = ''
background = '#f36943'
type = 'battery'
style = 'powerline'
background_templates = [
  '{{if eq "Charging" .State.String}}#b8e994{{end}}',
  '{{if eq "Discharging" .State.String}}#fff34e{{end}}',
  '{{if eq "Full" .State.String}}#33DD2D{{end}}',
]
invert_powerline = true

[blocks.segments.properties]
charged_icon = ' '
charging_icon = ' '
discharging_icon = ' '

# [[blocks.segments]]
# leading_diamond = ''
# trailing_diamond = ''
# template = '  {{ .CurrentDate | date .Format }} '
# foreground = '#ffffff'
# background = '#40c4ff'
# type = 'time'
# style = 'diamond'
# invert_powerline = true

# [blocks.segments.properties]
# time_format = '_2,15:04'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '╰─'
foreground = '#21c7c7'
type = 'text'
style = 'plain'

[[blocks.segments]]
template = ' '
foreground = '#e0f8ff'
type = 'status'
style = 'plain'
foreground_templates = ['{{ if gt .Code 0 }}#ef5350{{ end }}']

[blocks.segments.properties]
always_enabled = true
