Host mds git.mds.gov.br
    Hostname git.mds.gov.br
    User git
    IdentityAgent ~/.var/app/com.bitwarden.desktop/data/.bitwarden-ssh-agent.sock
    IdentityFile ~/.ssh/keys.d/bitwarden/gitlab_mds_ed25519.pub
    IdentitiesOnly yes
